#!/usr/bin/env python

import importlib
import os
import shutil
import sys


shutil.rmtree(".deps/", ignore_errors=True)
os.mkdir(".deps")
lines = sys.stdin.readlines()
if len(sys.argv) > 1:
    lines.append(sys.argv[1])
for line in lines:
    for mod in line.split(" "):
        mod = mod.strip()
        try:
            importlib.import_module(mod)
            with open(os.path.join(".deps", mod), 'a'):
                pass
        except ImportError:
            pass
